version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn superlists.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - /tmp/staging.superlists.abbase.xyz.sock:/tmp/staging.superlists.abbase.xyz.sock
    tmpfs:
      - /tmp
#    ports:
#      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.prod.db

volumes:
  postgres_data:
  static_volume: