version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn superlists.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=superlists
      - POSTGRES_PASSWORD=superlists
      - POSTGRES_DB=superlists_dev
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web
  selenium:
    container_name: selenium
    image: selenium/standalone-firefox
    expose:
      - "4444"

volumes:
  postgres_data:
  static_volume: